" configs
set nu
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent
filetype indent on

set relativenumber
set cursorline

colorscheme slate
if !exists("g:syntax_on")
    syntax enable
    filetype on
endif

" conveniency keybinds
inoremap < <><Esc>ha

inoremap >> >>
inoremap << <<

inoremap <C-d> <Esc>
inoremap <C-_> //<space>

nnoremap f ^
nnoremap b $

nnoremap <silent> <C-s> :vsplit <CR>
