# quick debugging shortcuts
alias vimrc="vim ~/.vimrc"
alias zshrc="vim ~/.zshrc"

# development speedup process
alias flask-setup="python3 -m venv venv; touch app.py; mkdir templates"
alias build-system="touch Makefile; mkdir Docker; touch Docker/Dockerfile; touch .gitignore; git init;"
alias whatshouldicode="python3 gen.py"

alias erotic="osascript ~/love.applescript"
alias coding="osascript ~/code.applescript"
alias songs="osascript ~/songs.applescript"

# prompt
user_value=$(sed 's#.*/##' <<< $(pwd))

# speed optim - remove comment and add $git_existence_status to prompt if you don't care about cd load times
# if `git rev-parse --is-inside-work-tree 2>/dev/null`; then
# 	 git_existence_status=" %F{magenta}git($(basename `git rev-parse --show-toplevel`))"
# else
# 	 git_existence_status=""
# fi
PS1="%F{cyan}zsh: ${user_value//$USER/~}%F{cyan} $ %F{white}"


foo () {
  if [[ $PWD == $HOME ]]; then
    source ~/.zshrc
  else
    source ~/.zshrc
  fi
}

chpwd_functions+=(foo)
